import{a as b,S as v,i}from"./assets/vendor-DHjmJuTs.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const P="52919144-2a7b1f23e18b84640824764ee",R="https://pixabay.com/api/",B=15;async function g(o,t=1){try{return(await b.get(R,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:B}})).data}catch(a){throw console.error("Axios error:",a),a}}const f=document.querySelector("#gallery");let S=new v(".gallery a",{captionsData:"alt",captionDelay:250});function q(){f.innerHTML=""}function m(o){const t=o.map(({webformatURL:a,largeImageURL:n,tags:e,likes:r,views:s,comments:w,downloads:_})=>`
      <li class="gallery_item">
        <a href="${n}">
          <img class="gallery_img" src="${a}" alt="${e}" loading="lazy" />
        </a>
        <div class="gallery_info_wrapper">
          <p class="gallery_info">Likes <span>${r}</span></p>
          <p class="gallery_info">Views <span>${s}</span></p>
          <p class="gallery_info">Comments <span>${w}</span></p>
          <p class="gallery_info">Downloads <span>${_}</span></p>
        </div>
      </li>`).join("");f.insertAdjacentHTML("beforeend",t),S.refresh()}const A=document.getElementById("search-form"),I=document.getElementById("search-input"),h=document.getElementById("loader"),u=document.getElementById("load-more");let l="",d=1,c=0;A.addEventListener("submit",async o=>{if(o.preventDefault(),l=I.value.trim(),!l){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}d=1,c=0,q(),p(),y();try{const t=await g(l,d);if(c=t.totalHits,t.hits.length===0){i.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits),c>t.hits.length?E():p()}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{L()}});u.addEventListener("click",async()=>{d+=1,p(),y();try{const o=await g(l,d);m(o.hits);const t=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery_item").length>=c?(p(),i.info({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):E()}catch{i.error({title:"Error",message:"Failed to load more images. Please try again later.",position:"topRight"})}finally{L()}});function y(){h.classList.remove("hidden")}function L(){h.classList.add("hidden")}function E(){u.classList.remove("hidden")}function p(){u.classList.add("hidden")}
//# sourceMappingURL=index.js.map
